version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.7
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: mysql
            active: true
            host: db
            port: 3306
            user: root
            password: to_haslo_nie_moze_zawierac_zabronionych_slow_przez_nastoletni_pe_el
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: to_haslo_nie_moze_zawierac_zabronionych_slow_przez_nastoletni_pe_el
