version: 0.2
            
phases:
  install:
    commands:
      - npm i -g prisma
  pre_build:
    commands:
  build:
    commands:
  post_build:
    commands:
      - cd server && ENDPOINT=http://$PRISMA_SERVER:4460 prisma deploy
