version: 0.2
            
phases:
  install:
    commands:
      - npm i prisma
  pre_build:
    commands:
  build:
    commands:
  post_build:
    commands:
      - ENDPOINT=http://$PRISMA_SERVER:4466 node -p process.env
      - cd server && ENDPOINT=http://$PRISMA_SERVER:4460 ../node_modules/.bin/prisma deploy
