version: 0.2
            
phases:
  install:
    commands:
      - npm i prisma
  pre_build:
    commands:
  build:
    commands:
  post_build:
    commands:
      - ls server
      - ls server/node_modules
      - cd server && ENDPOINT=http://$PRISMA_SERVER:4460 ../node_modules/.bin/prisma deploy
