Parameters: 
  InstanceTypeParameter: 
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - m1.small
      - m1.large
    Description: Enter t2.micro, m1.small, or m1.large. Default is t2.micro.
Resources:
  PrismaServer:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-f90a4880 # eu-west-1 (Irleand)
      KeyName: aws-key2
      SecurityGroups:
        - !Ref PrismaServerSG
      UserData: !Base64 |
        #!/bin/bash
        curl https://raw.githubusercontent.com/alufers/devbord/master/aws/prisma_install.sh | bash >>/var/log/userdata.log 2>&1
  PrismaServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow ssh and 4466 prisma port
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '4466'
        ToPort: '4466'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
